# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Yesdoing의 개발 블로그
tagline:          'Yesdoing의 개발 블로그'
description:      'Yesdoing이 프로그래밍을 개발하며 배우고 느낀점을 기록하는 블로그입니다.'
url:              https://yesdoing.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
logo:             '/public/logo.jpg'
author:
  name:           'LEE JANGHUI'
  url:            https://yesdoing.github.io

paginate:         5
paginate_path: '/blog/page:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:           https://github.com/yesdoing
facebook:         https://www.facebook.com/yesdoing

disqus:
  shortname: yesdoings-blog
